name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  Version:
    name: Version
    needs: [ci]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version_changed: ${{ steps.check_version.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for version change
        id: check_version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version)
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            VERSION_CHANGED=1
          else
            VERSION_CHANGED=0
          fi
          echo "version_changed=$VERSION_CHANGED" >> "$GITHUB_OUTPUT"

      - name: Get version
        if: ${{ steps.check_version.outputs.version_changed == '1' }}
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  Submit:
    name: Submit
    needs: Version
    if: ${{ needs.Version.outputs.version_changed == '1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        run: |
          # pnpm zip
          pnpm zip:firefox

      - name: Submit to stores
        run: |
          pnpm wxt submit \
            # --chrome-zip .output/*-chrome.zip \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
        env:
          # CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          # CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          # CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          # CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.Version.outputs.version }}"
          draft: false
          prerelease: false
          files: |
            # .output/*-chrome.zip
            .output/*-firefox.zip
            .output/*-sources.zip
